### PR TITLE
idiomatic kotlin fixes

### PR DESCRIPTION
**Pull request by ssouris**
- it: implicit name of a single parameter
- string interpolation
- otherwise is depricated use onErrorResume

### CODE REVIEW

**Comment by ssouris** [comment]
Hi, these are some minor idiomatic Kotlin fixes.
I'm really glad that I bumped into your repo because I was able to practice my Kotlin skills + Spring 5.
I thought just for reference to do this pull request. By all means, do not merge it if you don't want to :)

**Comment by eddumelendez** [comment]
Thanks for the PR @ssouris Can you please rebase your branch?

**Comment by ssouris** [comment]
@eddumelendez  I did the rebase you can check :)

**Comment by eddumelendez** [comment]
Merged. Thanks!

**Pull request merged**
