### PR TITLE
Use a nullable type, fix todo

### PR DESCRIPTION
**Pull request by rbatista**
- Some tests throw a nullpointer outside the `TODO` and it can be confuse to the developer. So in these cases it was replaced by a nullable type.
 - The `Schedullers.parallel()` throws an `IllegalStateException` when you try to run a blocking code inside it.  So the TODO description was updated to use `Schedullers.elastic()`

### CODE REVIEW

**Comment by eddumelendez** [comment]
@rbatista thanks. I think you submit this PR with a different email than personal. Can you confirm this? After that I will proceed with the merge

**Comment by rbatista** [comment]
Hey @eddumelendez, sorry about that. I amended the commit.

**Comment by rbatista** [comment]
I think this PR resolves #3.

**Comment by eddumelendez** [comment]
Merged. Thanks!

**Pull request merged**
